In [1]:
import numpy as np
import Robot
from SE3lib import SE3

In [8]:
scara = Robot.SCARA(2,1,1)
print(scara.S_tw)
print(type(scara.S_tw))

M = scara.zero
S = scara.S_tw
B = scara.B_tw

[[0.0, 0.0, 1.0, 0.0, 0.0, 0.0], [0.0, 0.0, 1.0, 0.0, -1.0, 0.0], [0.0, 0.0, 1.0, 0.0, -2.0, 0.0], [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]]
<class 'list'>


In [3]:
se3 = SE3()
w = se3.skew(scara.B_tw[0][:3])
v = scara.B_tw[0][3:]
print(w)
print(v)

[[ 0 -1  0]
 [ 1  0  0]
 [ 0  0  0]]
[0, 2, 0]


In [9]:
es_1 = se3.matexp('R',45,S[0])
es_2 = se3.matexp('R',45,S[1])
es_3 = se3.matexp('R',45,S[2])
es_4 = se3.matexp('P',0.9,S[3])
print(es_1)
matexps_s = [es_1,es_2,es_3,es_4]


[[ 0.70710678 -0.70710678  0.          0.        ]
 [ 0.70710678  0.70710678  0.          0.        ]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]


In [10]:
eb_1 = se3.matexp('R',45,B[0])
eb_2 = se3.matexp('R',45,B[1])
eb_3 = se3.matexp('R',45,B[2])
eb_4 = se3.matexp('P',0.9,B[3])
print(eb_1)
matexps_b = [eb_1,eb_2,eb_3,eb_4]


[[ 0.70710678 -0.70710678  0.         -0.58578644]
 [ 0.70710678  0.70710678  0.          1.41421356]
 [ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]]


In [6]:
js = se3.space_jacobian(matexps_s,scara.S_tw)
print(js)

[[ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 1.          1.          1.          0.        ]
 [ 0.          0.70710678  1.70710678  0.        ]
 [ 0.         -0.70710678 -0.70710678  0.        ]
 [ 0.          0.          0.          1.        ]]


In [7]:
jb = se3.body_jacobian(scara.zero,matexps_b,scara.S_tw)
print(jb)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 1.70710678e+00  1.21320344e-01  4.21718067e-16  0.00000000e+00]
 [ 7.07106781e-01 -7.07106781e-01 -2.82842712e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
